{
 "title": "API",
 "time": { "from": "2022-11-17T14:20:00.000Z", "to": "2022-11-17T15:40:00.000Z" },
 "panels": [
  {
   "title": "count request api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,6h),\n  count(hn) AS \"Count Request\"\nFROM predict_log\nWHERE\n  WEEKOFYEAR(timestamp) = (SELECT WEEKOFYEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1) and\n  YEAR(timestamp) = (SELECT YEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,6h)"
    }
   ]
  },
  {
   "title": "count request api",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,7d),\n  count(hn) AS \"Count Request\"\nFROM predict_log\nWHERE\n  WEEKOFYEAR(timestamp) = (SELECT WEEKOFYEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1) and\n  YEAR(timestamp) = (SELECT YEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1)\nORDER BY $__timeGroup(timestamp,7d)"
    }
   ]
  },
  {
   "title": "Update  time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Best model name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Hyperparameters",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Confusion Matrix",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(cag_confirm) as \"True Positive\"\nFROM predict_log\nWHERE\n  (pred_cag = 1 and cag_confirm = 1) and\n  (WEEKOFYEAR(timestamp) = (SELECT WEEKOFYEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1)) and\n  (YEAR(timestamp) = (SELECT YEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1))\nGROUP BY WEEKOFYEAR(timestamp)"
    },
    {
     "rawSql": "SELECT\n  count(cag_confirm) as \"False Positive\"\nFROM predict_log\nWHERE\n  (pred_cag = 1 and cag_confirm = 0) and\n  (WEEKOFYEAR(timestamp) = (SELECT WEEKOFYEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1)) and\n  (YEAR(timestamp) = (SELECT YEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1))\nGROUP BY WEEKOFYEAR(timestamp)"
    },
    {
     "rawSql": "SELECT\n  count(cag_confirm) as \"False Negative\"\nFROM predict_log\nWHERE\n  (pred_cag = 0 and cag_confirm = 1) and\n  (WEEKOFYEAR(timestamp) = (SELECT WEEKOFYEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1)) and\n  (YEAR(timestamp) = (SELECT YEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1))\nGROUP BY WEEKOFYEAR(timestamp)"
    },
    {
     "rawSql": "SELECT\n  count(cag_confirm) as \"True Negative\"\nFROM predict_log\nWHERE\n  (pred_cag = 0 and cag_confirm = 0) and\n  (WEEKOFYEAR(timestamp) = (SELECT WEEKOFYEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1)) and\n  (YEAR(timestamp) = (SELECT YEAR(timestamp) FROM predict_log ORDER BY timestamp DESC LIMIT 1))\nGROUP BY WEEKOFYEAR(timestamp)"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($TP + $TN) / ($TP + $FP + $FN + $TN)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$TP / ($TP + $FP)", "type": "math" },
    { "expression": "$TP / ($TP + $FN)", "type": "math" },
    {
     "expression": "2 * ($Precision * $Recall) / ($Precision + $Recall)",
     "type": "math"
    }
   ]
  }
 ]
}